services:
  app:
    build: 
      context: .
    ports: 
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      LANGUAGE: "it"
      BASE_URL: "/recipe-book"
    
  mongodb:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
volumes:
  mongodb_data_volume:
    external: false
